"""add categorias_imagens table

Revision ID: a29568b53a22
Revises: 001
Create Date: 2026-04-13 17:52:05.723185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a29568b53a22'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_imagens',
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('link', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('categoria')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categorias_imagens')
    # ### end Alembic commands ###
